//===-- Implementation header for exp2bf16 ----------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIBC_SRC___SUPPORT_MATH_EXP2BF16_H
#define LLVM_LIBC_SRC___SUPPORT_MATH_EXP2BF16_H

#include "src/__support/FPUtil/FEnvImpl.h"
#include "src/__support/FPUtil/FPBits.h"
#include "src/__support/FPUtil/ManipulationFunctions.h"
#include "src/__support/FPUtil/PolyEval.h"
#include "src/__support/FPUtil/bfloat16.h"
#include "src/__support/FPUtil/cast.h"
#include "src/__support/FPUtil/except_value_utils.h"
#include "src/__support/FPUtil/nearest_integer.h"
#include "src/__support/common.h"
#include "src/__support/macros/optimization.h"

// This is an algorithm for exp2(x) in bfloat16 which is correctly rounded for
// all rounding modes, based on the implementation of exp2bf16(x)
// from the RLIBM project at: https://people.cs.rutgers.edu/~sn349/rlibm

// Step 1 - Range reduction of edge cases:
// Find the largest value x for which exp2bf16(x) = +0.0
// x < log2(min subnormal bfloat16)
// Find the smallest value x for which exp2bf16(x) = +INF
// x > log2(max normal bfloat16)

// Step 2 - Range reduction to subnormal range:
// decompose x into sum of two parts - closest integer i and a fraction f
// exp2(x) = exp2(i + f) = exp2(i) * exp2(f)

// Step 4 - Polynomial approximation:
// Approximate the range reduced function exp2(f) on a domain (-0.5, 0.5)
// using a fourth degree polynomial P
// Generated by Sollya with the following command:
// > display = hexadecimal;
// > exp2 = 2^x;
// > I = [-0.5, 0.5];
// > P = fpminimax(exp2, 4, [|1, SG...|], I);
// > E = infnorm(exp2 - P, I);

// Step 4 - Output compensation:
// exp2(x) = exp2(i) * P(f)

namespace LIBC_NAMESPACE_DECL {
namespace math {

LIBC_INLINE constexpr bfloat16 exp2bf16(bfloat16 x) {
  using FPBits = typename fputil::FPBits<bfloat16>;
  FPBits x_bits(x);

  uint16_t x_u = x_bits.uintval();

  // special case where exp2bf16(NaN) = NaN
  if (LIBC_UNLIKELY(x_bits.is_nan())) {
    if (x_bits.is_signaling_nan()) {
      fputil::raise_except_if_required(FE_INVALID);
      return FPBits::quiet_nan().get_val();
    }
    return x;
  }

  // exp2bf16(x) = +0.0
  if (x_bits.is_neg() && x_u >= 0xc306U) { // x <= -0x1.0cp+7
    return FPBits::zero().get_val();
  }

  // exp2bf16(x) = +INF
  if (x_bits.is_pos() && x_u >= 0x4300U) { // x >= 0x1p+7
    if (x_bits.is_inf())
      return FPBits::inf().get_val();

    switch (fputil::quick_get_round()) {
    case FE_TONEAREST:
    case FE_UPWARD:
      fputil::set_errno_if_required(ERANGE);
      fputil::raise_except_if_required(FE_OVERFLOW);
      return FPBits::inf().get_val();
    default:
      return FPBits::max_normal().get_val();
    }
  }

  // range reduction to (-0.5, 0.5)
  float intPart = fputil::nearest_integer(x);
  float fracPart = x - intPart;

  // polynomial approximation of exp2(x) on (-0.5, 0.5)
  float poly = fputil::polyeval(fracPart,
                                0x1p0f, // Exp2(0) = 1
                                0x1.62e0dep-1f, 0x1.ec00d6p-3f, 0x1.ca13dcp-5f,
                                0x1.3ac75ep-7f);

  // output compensation
  float result = fputil::ldexp(poly, static_cast<int>(intPart));
  return fputil::cast<bfloat16>(result);
}

} // namespace math
} // namespace LIBC_NAMESPACE_DECL

#endif // LLVM_LIBC_SRC___SUPPORT_MATH_EXP2BF16_H
